config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="tasks/", permanent=True)),
    path("tasks/", include("task.urls", namespace="task")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    task_update_status,
    TagListView,
    TagCreateView,
    TagUpdateView, TagDeleteView
)


urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "<int:pk>/update-status/",
        task_update_status,
        name="task-update-status"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="tag-list"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    )
]

app_name = "task"

task/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=35, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "created_at"]

    def __str__(self):
        return self.content[:10] + "..."

task/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from task.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        input_formats=['%Y-%m-%dT%H:%M'],
    )

    class Meta:
        model = Task
        exclude = ("is_completed", )

    def clean_deadline(self):
        deadline = self.cleaned_data.get("deadline")

        if timezone.now() >= deadline:
            raise ValidationError("Invalid date for deadline")
        return deadline

task/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from task.forms import TaskForm
from task.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


def task_update_status(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = not task.is_completed
    task.save()

    return redirect("task:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("task:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("task:tag-list")

templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
         {% include "includes/sidebar.html" %}
      </div>
      <div class="col-sm-10">
        <div class="container">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'task:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task:tag-list' %}">Tags</a></li>
</ul>

templates/task/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Confirm delete tag
{% endblock %}

{% block content %}
  <div class="button-group">
    <h1>Delete tag?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Delete" class="btn btn-secondary">
      <a class="btn btn-primary" href="{% url 'task:tag-list' %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/task/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  {{ object|yesno:"Update tag,Add tag" }}
{% endblock %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/task/tag_list.html
{% extends "base.html" %}

{% block title %}
  Tags
{% endblock %}

{% block content %}
  <div class="title">
    <a href="{% url 'task:tag-create' %}" class="btn btn-primary add-task">Add tag</a>
    <h1>Tags</h1>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for tag in tag_list %}
        <tr>
        <th scope="row">{{ tag.name }}</th>
        <th scope="row"><a href="{% url 'task:tag-update' pk=tag.id %}" class="btn btn-primary">Update</a></th>
        <th scope="row"><a href="{% url 'task:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a></th>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Confirm delete task
{% endblock %}

{% block content %}
  <div class="button-group">
    <h1>Delete task?</h1>
    <form action="" method="post">
      {% csrf_token %}

      <input type="submit" value="Delete" class="btn btn-secondary">
      <a class="btn btn-primary" href="{% url 'task:task-list' %}">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  {{ object|yesno:"Update task,Add task" }}
{% endblock %}

{% block content %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block title %}
  TODO list
{% endblock %}

{% block content %}
  <div class="title">
    <a href="{% url 'task:task-create' %}" class="btn btn-primary add-task">Add task</a>
    <h1>TODO list</h1>
  </div>

  {% for task in task_list %}
    <div class="card">
      <div class="card-header">
        {% for tag in task.tags.all %}
          #{{ tag }}
        {% endfor %}
      </div>
      <div class="card-body">
        <div class="card-update">
          <a href="{% url 'task:task-update' pk=task.id %}" class="btn btn-primary">Update</a>
          <a href="{% url 'task:task-delete' pk=task.id %}" class="btn btn-primary">Delete</a>
        </div>
        <p class="card-text"><b>Content</b>: {{ task.content }}</p>
        <p class="card-text"><b>Created at</b>: {{ task.created_at }}</p>
         {% if task.deadline %}
          <p class="card-text"><b>Deadline</b>: {{ task.deadline }}</p>
          <p class="card-text {% if task.is_completed %} task-done {% else %} task-not-done {% endif %}"><b>Status</b>: {{ task.is_completed|yesno:"Done, Not done" }}</p>
         {% endif %}
        <a
            href="{% url "task:task-update-status" pk=task.id %}"
            class="{% if task.is_completed %}btn btn-secondary{% else %}btn btn-success{% endif %}">
          {{ task.is_completed|yesno:"Undo, Complete" }}
        </a>
      </div>
    </div>
  {% endfor %}
{% endblock %}